# Generated by Django 5.1.1 on 2025-01-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vendor_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
